#!/bin/sh
#PBS -N MPIMMM 
#PBS -m abe
#PBS -j oe
#PBS -k n
#PBS -l nodes=2:lab218:ppn=10,walltime=8:00:00
# 
cat $PBS_NODEFILE
cd ~pounds/mpi_starting 
#recompile on the node to make sure no issues with the compiler on hammer
mpicc -std=c99 -O2 mmm_mpi.c -o mmm_mpi -lm
n=`wc -l < $PBS_NODEFILE`
n=`expr $n / 10`
NETWORK="--gmca btl_tcp_if_include """10.30.165.0/8""""
HOSTS="--map-by ppr:1:node --hostfile $PBS_NODEFILE"
mpirun -np $n $NETWORK $HOSTS  mmm_mpi 
